### PR TITLE
 plugin does not work for dc version higher than 5.1.4 

### LINKED ISSUE #37: plugin doesn't work starting with DC 5.1.4
The plugin doesn't work starting with the release of DC 5.1.4 due to classpath changes.

### PR DESCRIPTION
**Pull request by ClaudiaPHI**
Fixes #37 

updated DC classpath and DC version

### CODE REVIEW

File: src/main/java/org/pentaho/di/profiling/datacleaner/ModelerHelper.java [hunk 1]
```diff
@@ -144,8 +144,10 @@ public static int launchDataCleaner(DataCleanerSpoonConfiguration dataCleanerSpo
 
         try {
             final String dcInstallationPath = dataCleanerSpoonConfiguration.getDataCleanerInstallationFolderPath()
-                    + "/DataCleaner.jar";
-            StringBuilder classPathBuilder;
+                    + "/DataCleaner.jar" + ";" + dataCleanerSpoonConfiguration.getDataCleanerInstallationFolderPath()
+                    + "/modules/*" + ";" + dataCleanerSpoonConfiguration.getDataCleanerInstallationFolderPath()
```
Comment (LosD) [inline src/main/java/org/pentaho/di/profiling/datacleaner/ModelerHelper.java:148]: Maybe not big enough to fix now, but it is getting a bit messy. I'd consider something like this:

```java
    private static String asPath(String... filenames) {
        return Stream.of(filenames).map(f -> getDataCleanerInstallationFolderPath() + "/" + f).collect(
                Collectors.joining(";"));
    }
    
   ...
      final String dcInstallationPath = asPath("DataCleaner.jar", "modules/*", "lib/*");
```
("filenames" as the argument name is maybe a bit wrong, being both a filename and paths, but I could't really conjure up anything better :))

Maybe not much gained now, but changing it later is a little simpler.

**Review by LosD — APPROVED** [review]
LGTM, but I have a single suggestion.

I'm not sure it's worth the trouble, so I'll leave it up to you if you want to do the change. If not, go ahead and merge :)

File: src/main/java/org/pentaho/di/profiling/datacleaner/ModelerHelper.java (hunk 1 above)
Comment (ClaudiaPHI) [reply src/main/java/org/pentaho/di/profiling/datacleaner/ModelerHelper.java:148]: Thanks for suggestion, but it's not worth the trouble right now.
