### PR TITLE
Bug/12 pdi blocked until dc finishes

### LINKED ISSUE #12: PDI is blocked/not responding while DC is running
I think we've accidentally taken up the main SWT dispatcher thread while waiting for the DC process to end now ... We should spawn a new thread to run the DC process through that.

image

### PR DESCRIPTION
**Pull request by ClaudiaPHI**
Fixes #12.

The swt threads were blocked because they were waiting for the process that launches DC to finish. 

```
 process.waitFor() 
 psrStdout.join();
 psrStderr.join(); 
```

### CODE REVIEW

**Comment by LosD** [comment]
But the thread _should_ block, so the exit value can be checked, and files cleaned up. Now it does neither.

It should just do the checking in a new thread.

**Comment by ClaudiaPHI** [comment]
The files are temporary, created with KettleVFS.createTempFile method so my guess is that they are deleted when Pentaho has stopped running.

File: src/main/java/org/datacleaner/kettle/configuration/DataCleanerConfigurationDialog.java [hunk 1]
```diff
@@ -189,11 +186,7 @@ public void widgetSelected(SelectionEvent event) {
                 labelVersion.setText(VERSION.trim() + " " + editionDetails.getVersion());
             }
         } catch (Throwable e) {
-            String errorMessage = "There was an unexpected error launching DataCleaner";
-            if (e instanceof IOException) {
-                errorMessage = "The DataCleaner installation path could not be found.Please set the path in the menu Tools:DataCleaner configuration";
-            }
-            new ErrorDialog(Spoon.getInstance().getShell(), "Error launching DataCleaner", errorMessage, e);
+           //Do nothing
```
Comment (LosD) [inline src/main/java/org/datacleaner/kettle/configuration/DataCleanerConfigurationDialog.java]: Couldn't this also use the JOptionPane? No error message seems dangerous. Or is it handled in the ModelerHelper (should that be _Modal_ Helper, btw?)? In that case I would remove that try/catch block completely, it's not very nice to swallow exceptions.

**Comment by LosD** [comment]
A single worry with a swallowed Exception, otherwise LGTM.

File: src/main/java/org/datacleaner/kettle/configuration/DataCleanerConfigurationDialog.java (hunk 1 above)
Comment (ClaudiaPHI) [inline src/main/java/org/datacleaner/kettle/configuration/DataCleanerConfigurationDialog.java]: The exception could occur if the DataCleaner configuration  has never been set and therefore the file doesn't exist. I do not think the user needs to see it.

**Comment by LosD** [comment]
Aaaaand my comment disappeared because of yet another update that was pushed directly to master (and then merged here). This needs to stop. _Nothing_ should be pushed to master without a very good reason.

File: src/main/java/org/datacleaner/kettle/configuration/DataCleanerConfigurationDialog.java [hunk 2]
```diff
@@ -184,7 +183,6 @@ public void widgetSelected(SelectionEvent event) {
             }
         } catch (Throwable e) {
             // Do nothing If the file doesn't exit 
-
```
Comment (kaspersorensen) [inline src/main/java/org/datacleaner/kettle/configuration/DataCleanerConfigurationDialog.java:187]: Nothing worsened by this PR, but I don't like swallowed exceptions either. At the very least we should log it, but if it is in deed "just" that a file does not exist, then it can be handled with a simple check instead of catching a very broad class of exceptions (throwables even).

**Comment by kaspersorensen** [comment]
Ehm I see some general exception handling issues here, but it does not seem to be in this PR. But to be constructive: I suggest that we soon have a pairing session about this with @ClaudiaPHI so that we are on the same page. I don't know what went on here but the outcome looks to be a bit dangerous. The codebase wasn't nice in the first place, but we should strive to improve that and always make sure we understand _why_ something is going wrong, not just patch it up with symptomatic treatment.

**Comment by kaspersorensen** [comment]
Please see #21 ... Tried to sort out some of this stuff ... In general I want us to take a bit more care of the code style in this project. We seem to be "accepting the bit-rot" and that's not so nice.

File: src/main/java/org/datacleaner/kettle/configuration/DataCleanerConfigurationDialog.java (hunk 2 above)
Comment (ClaudiaPHI) [inline src/main/java/org/datacleaner/kettle/configuration/DataCleanerConfigurationDialog.java:187]: The story was this one https://github.com/datacleaner/pdi-datacleaner/issues/10. 
That exception happens if DC was never configured before, and there is no configuration to show. Even if by mistake the file is not there by any other cause, it would be weird to show a message with "File not found" exception in a configuration dialog. And anyways the user can set it again, and the file will be recreated. 

@LosD  I wasn't aware I cannot make any short of decision, especially for a lousy configuration dialog.
